<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmation Required</name>
   <tag></tag>
   <elementGuidId>9620aaf8-bc44-4d8f-8536-306678fa7d0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dialogUpdateBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dialogUpdateBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dialogUpdateBtn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ae02033-5434-4210-b8af-cc1d50bab7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e897de4e-192c-43c4-b868-8179948651d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn searchbutton hover</value>
      <webElementGuid>8fb6d1fe-b475-4ccd-9658-3c9794e34756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>fa47e090-57f4-46bb-9f3c-9a6a931d26ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialogUpdateBtn</value>
      <webElementGuid>a95d2455-5e1b-4245-b359-bd96e1b26466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>72fc2e54-9276-4212-a5ea-93b9c89272d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogUpdateBtn&quot;)</value>
      <webElementGuid>af8758fe-f400-41d3-9bb3-d497d0871952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dialogUpdateBtn']</value>
      <webElementGuid>53e873d3-943b-49f6-9c41-a0706878e29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editConfModal']/div[3]/input</value>
      <webElementGuid>0a97db85-9d18-47a4-98c2-6ef8f98d0eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>02c4f1b3-16c3-4c8f-92d1-9b60833b71ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'dialogUpdateBtn']</value>
      <webElementGuid>20b8e5cd-1991-40bf-a188-b0dd26ed8d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
