<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>HRM</description>
   <name>HRM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>sandeepk@suntechnologies.com;</mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5a5fee4e-175f-4e67-bdc6-719637e5ef32</testSuiteGuid>
   <testCaseLink>
      <guid>b4bf913d-fca8-45e0-b677-b3a97e1f6a2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Login_To_HRM</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>becabbf9-72ec-4d94-b18b-7a3552fcfeb7</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/HRM_Roles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>becabbf9-72ec-4d94-b18b-7a3552fcfeb7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b936fe9c-6b5e-43dd-9916-953214dfc68e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>becabbf9-72ec-4d94-b18b-7a3552fcfeb7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c2af3fef-4209-46fb-981c-fe0f96f250f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e95fb447-5f9e-4406-9783-67a04b8c8b78</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Logout_HRM</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0cf2ea3d-5f13-4cfe-b98a-b77d3ed5ef76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Validate_User_Management_Admin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d0abb9b9-9f3b-414c-9f5c-b0618f44bee3</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/HRM_Roles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d0abb9b9-9f3b-414c-9f5c-b0618f44bee3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f1d89f82-5816-4213-bfd3-fe6477dfb306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d0abb9b9-9f3b-414c-9f5c-b0618f44bee3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f5d72396-b9dc-439e-b7fa-eedcfa378009</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a84e433-b0e9-4d52-bae7-69137903a535</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Validate_Leave_Submission_And_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd190fed-8b96-4492-b3fa-acc55873777b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad89f7b-bca3-40be-beab-8f824bcaa3a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>635b76c5-8ab4-4a3b-a642-575d7dd2bac9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8f9d857-b602-4d22-a71b-9e594716356f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Validate_TimeSheet_Submission_And_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f49786-d008-4fbe-9eb5-9be9cabc792a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55fe8f28-8bcd-4fa8-9f69-2cc549715cc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aee0205-3cc2-4a4d-a734-d11cd533828e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ca507f3-5b81-4aaf-82c9-465c23769708</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <iterationNameVariable>
         <defaultValue>'manikantak'</defaultValue>
         <description></description>
         <id>26666deb-9b9b-4e5b-b8be-652ef42a8dd9</id>
         <masked>false</masked>
         <name>role_User</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Validate_Submit_Expense_By_User</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>14f71c40-0435-4fdb-a78e-5babbcc82c7d</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/HRM_Roles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>14f71c40-0435-4fdb-a78e-5babbcc82c7d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>26666deb-9b9b-4e5b-b8be-652ef42a8dd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>14f71c40-0435-4fdb-a78e-5babbcc82c7d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f93680c5-9324-4b70-b218-9e03612bec0d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
