<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>HRM</description>
   <name>HRM</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5a5fee4e-175f-4e67-bdc6-719637e5ef32</testSuiteGuid>
   <testCaseLink>
      <guid>0cf2ea3d-5f13-4cfe-b98a-b77d3ed5ef76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Validate_User_Management_Admin</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>d0abb9b9-9f3b-414c-9f5c-b0618f44bee3</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/HRM_Roles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d0abb9b9-9f3b-414c-9f5c-b0618f44bee3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f1d89f82-5816-4213-bfd3-fe6477dfb306</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d0abb9b9-9f3b-414c-9f5c-b0618f44bee3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f5d72396-b9dc-439e-b7fa-eedcfa378009</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a84e433-b0e9-4d52-bae7-69137903a535</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Validate_Leave_Submission_And_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd190fed-8b96-4492-b3fa-acc55873777b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad89f7b-bca3-40be-beab-8f824bcaa3a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>635b76c5-8ab4-4a3b-a642-575d7dd2bac9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8f9d857-b602-4d22-a71b-9e594716356f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Validate_TimeSheet_Submission_And_Approval</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f49786-d008-4fbe-9eb5-9be9cabc792a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55fe8f28-8bcd-4fa8-9f69-2cc549715cc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aee0205-3cc2-4a4d-a734-d11cd533828e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
