<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HRM_Leave_Approval</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>93ccee1e-a1e7-4185-99dc-ac09a0df26cd</testSuiteGuid>
   <testCaseLink>
      <guid>e2f07515-939c-4199-a18d-6486cc936ceb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Validate_Leave_Applied_By_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd190fed-8b96-4492-b3fa-acc55873777b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad89f7b-bca3-40be-beab-8f824bcaa3a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c1fdab69-7f59-4683-9159-8e35080d1d28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Validate_Leave_Approval_By_Manager</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5144519c-a3b6-4665-a494-7ca7f7281cf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98178acc-d1ad-4661-b7ee-32fdcb974e52</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
