<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HRM_Timesheet_Approval</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d60c0691-424f-4d81-b9f3-248c9f98dff1</testSuiteGuid>
   <testCaseLink>
      <guid>58f2b781-d33f-4e18-88b6-9e381219f1fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Validate_Submit_Timesheet_By_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56f49786-d008-4fbe-9eb5-9be9cabc792a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55fe8f28-8bcd-4fa8-9f69-2cc549715cc4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cecfe32d-fed7-4f23-a849-a992ef3389b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Validate_Timesheet Approval_By_Manager</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e30f2df4-8398-4b09-ba04-0a07dc49d34f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>499ce728-d9b1-43b6-804f-cbed4864e289</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
