<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Leave</name>
   <tag></tag>
   <elementGuidId>0fcc9ab4-a05a-47cb-96a1-db1730462c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_leave_viewLeaveModule > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_leave_viewLeaveModule']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Leave&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>25efd319-d7cd-4993-8bf9-c2d5593d7324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave</value>
      <webElementGuid>59e3f0ed-bd3f-460a-9b10-4b7adfba8e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_leave_viewLeaveModule&quot;)/b[1]</value>
      <webElementGuid>64b5374c-c415-4ee5-a503-7d547b773406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_leave_viewLeaveModule']/b</value>
      <webElementGuid>3606cd19-91a8-4334-ad10-504b18d5600a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee List'])[1]/following::b[1]</value>
      <webElementGuid>b1c6ad7f-c1e4-4587-b10c-34d9ae44825b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIM'])[1]/following::b[1]</value>
      <webElementGuid>ca1ff7f3-d260-49f5-9bbc-e827e9e27154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::b[1]</value>
      <webElementGuid>24072d26-6470-4818-972e-2a48c4c04dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Leave'])[1]/preceding::b[1]</value>
      <webElementGuid>371c4f9b-845e-4865-83f4-0f1056e5d6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave']/parent::*</value>
      <webElementGuid>878a60c2-ed27-4b12-bec8-a1adbae175fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/b</value>
      <webElementGuid>d704cc1f-a5ee-4143-b246-704b9cf1b72d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Leave' or . = 'Leave')]</value>
      <webElementGuid>c1ea1861-bc98-46ad-bba4-408006e3041e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
