<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__applyleavetxtFromDate</name>
   <tag></tag>
   <elementGuidId>399e3426-f06f-44c2-9fdf-d8ab13178926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#applyleave_txtFromDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='applyleave_txtFromDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;From Date *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d7bd513-848a-4636-a3ba-bb9c74de6500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applyleave_txtFromDate</value>
      <webElementGuid>d31b5a05-84a3-4de0-9694-385e394eb9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cab0900e-5952-4b25-af50-eb4d18099511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applyleave[txtFromDate]</value>
      <webElementGuid>56f8e671-0342-4949-b82d-315e0065d4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar hasDatepicker</value>
      <webElementGuid>cfd84194-e2d6-4a44-98bb-97b2dea4206d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applyleave_txtFromDate&quot;)</value>
      <webElementGuid>b8ea14f6-1036-4f59-bb7c-572c80ca85bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='applyleave_txtFromDate']</value>
      <webElementGuid>bee432e0-62f8-44ee-98bf-3bb6b7099c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLeaveApply']/fieldset/ol/li[3]/input</value>
      <webElementGuid>bcc80409-6b47-4fca-8c92-850d0fbfa7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>777a9e90-7b5b-4e0a-b239-5e6a0284d9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'applyleave_txtFromDate' and @type = 'text' and @name = 'applyleave[txtFromDate]']</value>
      <webElementGuid>768b0c77-3c58-4241-b372-69e0f7bd2636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
