<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Comment_ApplyLeave</name>
   <tag></tag>
   <elementGuidId>6c3bfef8-88f0-4755-98fe-e2d0a16054b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#applyleave_txtComment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='applyleave_txtComment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Comment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>94154ba7-3674-49e2-9d61-9171f2d833b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ec034991-7eea-4f4b-a0e0-1f074001730f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b2d22069-a71a-44ee-8472-8d8438133275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>applyleave[txtComment]</value>
      <webElementGuid>bf5e29dd-9f14-4836-939e-bdea9c73a5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applyleave_txtComment</value>
      <webElementGuid>0de0e2f1-5cfe-472d-b705-1f484aca9e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applyleave_txtComment&quot;)</value>
      <webElementGuid>fdf10d6b-51fb-44b3-94be-c08544f5d0f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='applyleave_txtComment']</value>
      <webElementGuid>5ebdabd9-3faf-4bc9-87c5-145c97187e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLeaveApply']/fieldset/ol/li[9]/textarea</value>
      <webElementGuid>ab2eb720-3b63-41cc-9819-4333abb515b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>367196cb-039a-4473-a068-b162b5b8b5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'applyleave[txtComment]' and @id = 'applyleave_txtComment']</value>
      <webElementGuid>19269d8e-68de-45f1-9ae4-e6d85bddfb60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
