<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View My Expense</name>
   <tag></tag>
   <elementGuidId>c9bfd9bf-a67a-4d10-a4c6-7812fb64f2d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_expense_viewMyExpenseReport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_expense_viewMyExpenseReport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View My Expense&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2f39458-671d-4fb8-8f67-d403683c2d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/symfony/web/index.php/expense/viewMyExpenseReport</value>
      <webElementGuid>c1858ca4-14e1-4b29-b6f5-a27f222a4c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_expense_viewMyExpenseReport</value>
      <webElementGuid>b2ffab97-2459-4d3a-af71-28b5be8a0d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View My Expense</value>
      <webElementGuid>37f115b1-ce00-49cf-9af6-7d6caac7bc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_expense_viewMyExpenseReport&quot;)</value>
      <webElementGuid>8c6dd576-7f20-422d-8a4d-5388942cb45a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_expense_viewMyExpenseReport']</value>
      <webElementGuid>fcaf4ea3-fac5-4fe9-aa4b-ebea9eed0cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/ul/li[4]/ul/li[2]/ul/li/a</value>
      <webElementGuid>fe6075c0-aae9-4b58-a6de-14a4ce3ea3ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View My Expense')]</value>
      <webElementGuid>21b6f821-f7a8-495c-ba6b-aba3650e3ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Expense'])[1]/following::a[2]</value>
      <webElementGuid>aec54f3f-19d6-4340-aa9d-af94dd7a8465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense'])[1]/following::a[3]</value>
      <webElementGuid>88b6abce-8692-4a60-8c4e-a0cc33a893e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Employee Expense'])[1]/preceding::a[1]</value>
      <webElementGuid>a41834b6-9dcf-443e-af62-98fb6af00042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expense Report'])[1]/preceding::a[2]</value>
      <webElementGuid>f6ed5c0a-1b75-4921-8df7-2f8148c5362a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View My Expense']/parent::*</value>
      <webElementGuid>c1a3e887-0c7f-429c-b456-10faa048e7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/symfony/web/index.php/expense/viewMyExpenseReport')]</value>
      <webElementGuid>5a4ab149-92b8-4721-a490-5dcdc9d92cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/ul/li/a</value>
      <webElementGuid>da4edf0d-5f21-4974-844c-7f007377a44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/symfony/web/index.php/expense/viewMyExpenseReport' and @id = 'menu_expense_viewMyExpenseReport' and (text() = 'View My Expense' or . = 'View My Expense')]</value>
      <webElementGuid>e3021115-4b44-44c6-a2ee-81d8d5420487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
