<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date</name>
   <tag></tag>
   <elementGuidId>4fcf400e-c9f3-417c-964b-10c9a654e4ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expense_date_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#expense_date_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#expense_date_0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>991cfcec-1c6d-4cf8-aff4-cba06795ce8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expense_date_0</value>
      <webElementGuid>cd2f98b6-ae77-48ed-9533-7c0bd9446f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tdate calendar hasDatepicker</value>
      <webElementGuid>b9b96ee8-c43e-4026-968b-f4845eab2a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce68937a-ec07-4c12-bcac-b384bda4db26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>initialRows[0][Date]</value>
      <webElementGuid>f19f342f-75e4-482d-9d04-83e7a9946625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expense_date_0&quot;)</value>
      <webElementGuid>94ce1f87-3b31-4e8f-9e46-fc915063e3e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expense_date_0']</value>
      <webElementGuid>58772403-50c1-4938-9d1f-5c0f8ea91f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='travel_expense']/fieldset/ol[2]/table/tbody[2]/tr/td[2]/input</value>
      <webElementGuid>799fc446-888d-4b58-a392-56c6f8fc9a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>d7d0e39f-3d78-434d-a4cd-9809cf4d9cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'expense_date_0' and @type = 'text' and @name = 'initialRows[0][Date]']</value>
      <webElementGuid>9cece838-f266-4967-b44d-005869731b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
