<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ExpenseAttachment</name>
   <tag></tag>
   <elementGuidId>a8bf1bef-af2d-4c0c-bfad-d7f158fefef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='initialRows_0_attachment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#initialRows_0_attachment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#initialRows_0_attachment</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6eb7c4f-b01f-41b7-89d6-3d08304c757e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment</value>
      <webElementGuid>a7bfccc8-869d-4640-aff5-b512de210eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>c0b1f9cf-ba1e-40b5-bcc6-582ec8a0139a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>initialRows[0][attachment]</value>
      <webElementGuid>7814bbc3-e140-4e02-92f4-28375e1fbd31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>initialRows_0_attachment</value>
      <webElementGuid>094aed4a-6fb4-4d09-9685-86864781decb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initialRows_0_attachment&quot;)</value>
      <webElementGuid>688cb368-a41b-4ff9-9d7f-3f18ceced8fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='initialRows_0_attachment']</value>
      <webElementGuid>ea48ccbd-99f0-40cb-bb4b-15ab1e528233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='travel_expense']/fieldset/ol[2]/table/tbody[2]/tr/td[6]/input</value>
      <webElementGuid>5e06a34f-c1ce-4ad6-95fd-7eb79f346023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>9bfd336f-b24a-4186-9875-5046360ae5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'initialRows[0][attachment]' and @id = 'initialRows_0_attachment']</value>
      <webElementGuid>34d778a3-e9a6-44c2-8a3c-c4bdc4fddb55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
