<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Edit User</name>
   <tag></tag>
   <elementGuidId>15b2f5d7-776c-47dc-94fc-ce4333b64923</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='UserHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Edit User&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>11471566-2dc1-4438-af99-405a6c1fe7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserHeading</value>
      <webElementGuid>d86bae1f-3934-486e-8ca2-0ca0425a6903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit User</value>
      <webElementGuid>b308709a-6a66-46cc-9e0e-f6a32d577a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserHeading&quot;)</value>
      <webElementGuid>97ab0885-be91-41ba-8220-1d5a2f061fef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='UserHeading']</value>
      <webElementGuid>37a2c9e3-4cd0-4b98-ba26-43659c96098e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='systemUser']/div/h1</value>
      <webElementGuid>0f630ce4-de31-46f3-85e4-8be02502fa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add User'])[1]/following::h1[1]</value>
      <webElementGuid>b458a4d5-c595-499e-83ef-fc064165da55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[2]/following::h1[1]</value>
      <webElementGuid>b2478498-24c9-4c3c-a7fc-8976e94b0715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If user role is a Admin Controller, Assign atleast one sub unit to Admin Controller.'])[1]/preceding::h1[1]</value>
      <webElementGuid>a79aa544-e6da-484c-82cf-049b7764dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Role'])[1]/preceding::h1[1]</value>
      <webElementGuid>2347c59d-3e67-4162-9959-53a18cfeb01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit User']/parent::*</value>
      <webElementGuid>6dac3a8a-6e0c-410e-998a-ba98b6ddf9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>29e8982a-70ba-40b6-861d-a13bc4759ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'UserHeading' and (text() = 'Edit User' or . = 'Edit User')]</value>
      <webElementGuid>6c082102-5b21-41b2-b8d0-f095dc2e2c27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
