<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirmation Required_dialogUpdateBtn</name>
   <tag></tag>
   <elementGuidId>abcaa7fa-e32b-41fe-9772-5b1bd784c7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dialogUpdateBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dialogUpdateBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dialogUpdateBtn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20cbc539-fa56-4b93-9c21-d1b4566ab325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>115d2c6a-bbbe-4f41-aec6-4d9a84073360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn searchbutton hover</value>
      <webElementGuid>5dd16268-a301-44c7-b38e-8073cca091e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>36b2d569-7962-4f9b-b23c-6a64bca7052f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialogUpdateBtn</value>
      <webElementGuid>31cbffe8-366f-4af0-a81a-857783c54a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>77828d34-df6b-46cd-b88f-74f0710ccf17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogUpdateBtn&quot;)</value>
      <webElementGuid>68f95460-d0da-444e-867a-a058463ac743</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dialogUpdateBtn']</value>
      <webElementGuid>e56b3860-a584-407c-800d-5e7611f0d11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='editConfModal']/div[3]/input</value>
      <webElementGuid>6497693e-c459-45db-b9a0-715128eb804b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>be59202a-58ab-4779-9e2e-03301314affc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'dialogUpdateBtn']</value>
      <webElementGuid>62303d4d-2ccb-4196-9fea-2f545de4fd00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
