<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_searchSystemUseruserName</name>
   <tag></tag>
   <elementGuidId>02cc6fd5-5e7a-423a-baa2-1321be7b067c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchSystemUser_userName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchSystemUser_userName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Username&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cb0a26a-eeb0-4903-851a-a924974709c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b10341e7-43dd-41c9-825b-5306cb8a294d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchSystemUser[userName]</value>
      <webElementGuid>9062aeb8-d4ec-480e-bd39-c69217478ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchSystemUser_userName</value>
      <webElementGuid>bc151e72-8a2b-4345-8afc-bef3a3ebbea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchSystemUser_userName&quot;)</value>
      <webElementGuid>4d00173e-9f1b-4e24-9658-75f17fa40184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchSystemUser_userName']</value>
      <webElementGuid>5c9770fc-9ab6-4689-8a7a-fc3135f26568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>f986bb8c-a771-4e6a-970c-c350045b7844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/ol/li/input</value>
      <webElementGuid>3e15ffb9-1b0f-4177-97ca-36d1b28c14cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchSystemUser[userName]' and @id = 'searchSystemUser_userName']</value>
      <webElementGuid>8382a563-64c3-4155-b4a6-edb2d3109076</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
