<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AdminAdmin ControllerESSTeam Lead</name>
   <tag></tag>
   <elementGuidId>dc588b49-3ed4-4a3c-9862-efa80058902e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#systemUser_userType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='systemUser_userType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;User Role&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>def26511-f9ce-4303-bdfd-053268c6f6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formSelect</value>
      <webElementGuid>ebfee2ef-e961-4698-aee0-c99ec082204a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4a591a02-d7ef-4450-a7bd-f48a3aa4f870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>systemUser[userType]</value>
      <webElementGuid>d011b1f6-e8a4-4991-b0a0-f6149d84f09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>systemUser_userType</value>
      <webElementGuid>43b37cc6-4619-48f4-a372-067748d227f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Admin
Admin Controller
ESS
Team Lead
</value>
      <webElementGuid>7a4c9d4d-d41f-4840-8f12-dcd5f5e6c110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;systemUser_userType&quot;)</value>
      <webElementGuid>c8bccfe6-8ebf-4c62-863b-ccac27f95efc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='systemUser_userType']</value>
      <webElementGuid>9336a163-d107-4d58-b100-170d19e73743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSystemUser']/fieldset/ol/li/select</value>
      <webElementGuid>b0ae9ec0-1e91-4a0d-b35e-b2a69e9eac85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Role'])[1]/following::select[1]</value>
      <webElementGuid>a7f9192b-fdb5-47e5-a383-6bc47a0c067c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If user role is a Admin Controller, Assign atleast one sub unit to Admin Controller.'])[1]/following::select[1]</value>
      <webElementGuid>fb70251a-4532-4bae-ba8f-525dfd9a2db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::select[1]</value>
      <webElementGuid>11405c56-76b2-434c-8e08-6d0b53110d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ca9f9800-073e-451b-8e2a-c8c079130ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'systemUser[userType]' and @id = 'systemUser_userType' and (text() = '
Admin
Admin Controller
ESS
Team Lead
' or . = '
Admin
Admin Controller
ESS
Team Lead
')]</value>
      <webElementGuid>8412e30a-98b1-48f4-a6b9-4888c553592d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
